### ISSUE TITLE
IQ Correction?

### ISSUE THREAD

**Issue by EricFROL** [SatDump/SatDump#427]
Is it possible to add the IQ Correction option?? I have a DC Spike that makes imposible to decode any signal.

**Comment by EricFROL** [comment]
Not working...

**Comment by JVital2013** [comment]
Hmm, removing DC spike works for some samples I tried. What are your experiencing that makes it look like IQ correction is not working? Again, you're still going to see the spike on the FFT/waterfall; it just removes it behind-the-scenes before demodulation.

Ideally, if you could share a baseband recording that you can't demodulate due to the DC spike, that would be amazing.

**Comment by EricFROL** [comment]
Closing because lost interest in solving this.
I'm now using Airspy mini instead of rtlsdr, so theres no dc spike now.
