### ISSUE TITLE
(D) Set RTL-SDR AGC to 0 [16:00:16 - 24/10/2023] (D) Set RTL-SDR Gain to 490

### ISSUE THREAD

**Issue by f6bvp** [SatDump/SatDump#453]
When setting RTLsdr AGC using slider from 0 to maximum,  RTL gain is displayed 490 on console screen.

[16:04:52 - 24/10/2023] (D) Set RTL-SDR AGC to 0
[16:00:16 - 24/10/2023] (D) Set RTL-SDR Gain to 490

However this gain is most probably 49 rather than 490.
for 49 dB is the maximum that can be set using slider LNA Gain

When moving the slider intermediate Gain are also displayed with 10 times the right value.

By the way,  I suppose message (D) Set RTL-SDR AGC to 0
means AGC is OFF 
and
(D) Set RTL-SDR AGC to 1
means AGC is ON

73 de Bernard, f6bvp / ai7bg

**Comment by JVital2013** [comment]
Hello,

Thanks for the feedback! Indeed, RTL-SDR gains were displaying 10 times the right value. This is due to how the API behind-the-scenes accepts gain values. However, SatDump logs the same value the CLI/UI in other places that do the same thing (MiriSDR). So, the bug will be fixed momentarily!

As for the AGC question: yes, 0 is off/no and 1 is on/yes. This shorthand is used several places throughout the log, including AGC and Bias-T status.
