### ISSUE TITLE
Json/lua error when creating cloud overlay composite of NOAA APT

### ISSUE THREAD

**Issue by Woutvstk** [SatDump/SatDump#527]
**Description of the issue**

In release 1.1.0, NOAA APT composites were added that were found in WXtoIMG. When I try to create Clouds_underlay/MCIR/MSA/MCIR_rain composites I get an error: 
 ```Error generating composite! lua: error: [json.exception.type_error.302] type must be string, but is null```

**Version (Eg, 1.0.0, CI Build 171)**
I'm using latest (as of 24/11/2023) nightly build for windows x64 and a baseband recording from an RTL-SDR with SDR#

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
I am not very familiar with C++ or lua myself but I have taken a look in the source code files.
I found these composite options under "avhrr_apt" in the `\SatDump-nightly\satdump_cfg.json` file. 
Under "avhrr_apt": Clouds_underlay, MCIR and MSA all refer to a lua script: `\SatDump-nightly\resources\scripted_compos\underlay_with_clouds.lua`. The "MCIR rain" composite refers to `\SatDump-nightly\resources\scripted_compos\underlay_with_clouds_lut.lua` and probably is a similair issue.

**Comment by ZbychuButItWasTaken** [comment]
Hi!
There is currently a lot of work being done on NOAA APT and composites in general, so pretty much all composites are going to change. 
However, thanks for reporting the issue!
(@RAD750)

**Comment by RAD750** [comment]
Hi! 
The most likely cause of your issue is that when you are using a baseband recording, **you need to specify the EXACT date and time of when the baseband recording starts** by unchecking the `Auto` box in `Start Timestamp` before you are starting the decode. **Remember this timestamp is in UTC time!**.
![immagine](https://github.com/SatDump/SatDump/assets/12469744/caeeb7fc-bc55-4004-afaf-8ef8158b254b)
Usually copying the timestamp from the baseband file name works good enough, provided you convert it to UTC.

The composite generator needs this information in order to determine which parts of the image is land and which is sea/ocean, so it can apply different enhancements. Additionally, it needs it to generate the map.

I'll try to make sure a more explicative error message comes up in the future, if indeed this turns out to be an issue.

An additional tip I can give you is to avoid using baseband recordings altogether and instead switch to using audio recordings as detailed [here](https://www.a-centauri.com/articoli/noaa-poes-satellites-reception). It not only wastes less disk space, but also the timestamp can be recognized automatically.

If the issue still persists, I'd need two things:
1. a screenshot showing the Products tab, with the name of satellite and time showing
2. The baseband recording (you can upload it e.g. to swisstransfer.com) 

Thanks :)
