### ISSUE TITLE
Warning message "LRIT CRC is invalid"

### ISSUE THREAD

**Issue by kd4uwu** [SatDump/SatDump#594]
Can someone assist me as to what this error is and how to correct it ?
![IMG_20240111_191608876](https://github.com/SatDump/SatDump/assets/118581996/c3ef63d0-8f9f-448a-9ed1-c90971e98f0f)

**Comment by rtlsdrblog** [comment]
(If it's not the SNR):

If you're running a sample rate of 2.56 MSPS, make sure that you do not change the PPM value from 0, otherwise the RTL-SDR will start dropping samples which can cause this.

The reason is that the RTL-SDR is only stable at 2.56 MSPS, and adjusting the PPM slightly changes the sample rate, pushing it into a sample rate that drops samples.

Alternatively, you can go to 2.4 MSPS and setting the PPM will work fine.

**Comment by JVital2013** [comment]
Hi @kd4uwu, do you need any further assistance with this issue?

**Comment by JVital2013** [comment]
I'll close this since we haven't heard from you, but if you need any specific help, feel free to reach back out!
