### ISSUE TITLE
Add time zone selector in settings for the scheduler

### ISSUE THREAD

**Issue by JimmyeJones** [SatDump/SatDump#679]
**Add time zone selector in settings for the scheduler**
This feature will greatly help me when preparing for satellite passes

Thanks in advance :)

**Comment by Aang23** [comment]
What do you mean exactly? Simply show them for your local timezone as to not have to do the conversion manually?

**Comment by JVital2013** [comment]
This has been requested multiple times by many different people, so I just implemented it for the scheduler/autotrack UI only. Since this is display-only, I see no harm in it here - but it will show a timezone abbreviation when enabled to avoid confusion.

All other data (anything logged, saved to a file, etc), should not and will not be in local time in my opinion, as it causes ambiguity. 

![image](https://github.com/user-attachments/assets/58f2a21b-10a5-40b9-970a-9079762db2cb)
