### ISSUE TITLE
[question] Why keep XP support?

### ISSUE THREAD

**Issue by alsldlflglhljlk** [SatDump/SatDump#777]
I was recently looking through the GitHub Actions tab for SatDump and found out there was some code being compiled for Windows XP, even though it was depreciated a very long time ago. Keeping XP support would simply take more work and may open up security holes with the now insecure networking. Furthermore, very few people even use XP anymore, so why keep support for it?

**Comment by JVital2013** [comment]
Agreed - this was mostly a pet project to see if it could be done (don't be surprised if it's not the last of those you see...). It's not the recommended way to do things for sure, for a whole pile of reasons.

That being said, I left it on a branch - in a secondary actions workflow - so that others can use it if they really need to. After all, I successfully decoded GOES HRIT, NOAA APT/DSB, and METEOR LRPT on a XP-period machine - so there's no reason to keep others from doing the same, if they really want/need to. HRPT seemed fine as well but that might require more oomf for live decoding. It's also the only build of SatDump for Windows that works on "modern" 32-bit at this time - which again, is not recommended, but at least the option is available. Keeping it around does not open up security holes on the main branch because XP is not considered for core development.

The Windows XP build plasters a warning in the log that it's not really supported, and not to open issues about it. I see you ignored the message in more than one way (just kidding! 😄)

This branch did take a bit of time to get going initially, but at this point, I don't plan on putting much extra energy into it. Merging new features into the XP branch only takes a few minutes every few weeks (read: whenever I feel like it), so I plan to roughly keep it up until Microsoft removes the XP toolset from Visual Studio, Github removes said toolchain from their CI runners, or SatDump changes in such a way that merging new features would be impractical or too time-consuming.
